config/routes.rb
namespace :will_ship do
  get :configure
  get :force_update
end

resources :will_ship

app/models/harbor.rb
class Harbor < ActiveRecord::Base
  unloadable

  belongs_to :project
  has_many :shipped_targets, dependent: :destroy
  has_many :shipped_changes, dependent: :destroy
  belongs_to :custom_field
end

app/models/shipped_change.rb
class ShippedChange < ActiveRecord::Base
  unloadable

  belongs_to :harbor
  belongs_to :changeset
end

app/models/shipped_target.rb
class ShippedTarget < ActiveRecord::Base
  unloadable

  belongs_to :harbor
  belongs_to :issue
end

app/controllers/will_ship_controller.rb
class WillShipController < ApplicationController
  unloadable
  before_filter :require_admin, except: [:force_update]
  before_filter :find_harbor, only: [:edit, :destroy]

  def new
    @harbor = Harbor.new
    @projects = Project.all
    @custom_fields = IssueCustomField.where('field_format in (?)', %w(int bool string text))
  end

  def edit
  end

  def create
    harbor = Harbor.new params[:harbor]
    if harbor.save!
      flash[:notice] = 'New Harbor just created!'
      redirect_to action: 'configure'
    else
      flash[:error] = 'Error!'
      redirect_to :back
    end
  end

  def destroy
    if @harbor.destroy
      flash[:notice] = 'Removed!'
    else
      flash[:error] = 'Error!'
    end

    redirect_to action: 'configure'
  end

  def configure
    @harbors = Harbor.all
  end

  def force_update
    issue = Issue.find params[:issue_id]
    return unless issue.present?
    result = issue.check_harbors!

    if result == true
      flash[:notice] = 'All Harbors checked! If we shipped we will see.'
      redirect_to :back
    else
      @harbors = result
      render 'empty_harbors'
    end
  end

  protected

  def find_harbor
    @harbor = Harbor.find params[:id]
  end
end

app/views/hooks/will_ship/_view_issues_show_description_bottom.html.erb
<% if @issue.project.harbors.any? %>
  <hr/>
  <div class='description'>
  <div class="contextual">
    <%= link_to 'Update', {:action => 'force_update', :controller => 'will_ship', :issue_id => @issue.id}, :class => 'icon icon-reload' %>
  </div>
  <p><strong>Shipping Status</strong>
  <% if @issue.shipped_targets.any? %>
    <i>checked <%= time_tag(@issue.shipped_targets.last.updated_at) %> ago</i>
  <% end %>
  </p>
  <p>
    <% if @issue.shipped_targets.any? %>
      <ul>
        <% @issue.shipped_targets.each do |t| %>
          <% if t.shipped %>
            <li class="icon icon-shipped">
              <%= t.harbor.name %>
            </li>
          <% else %>
            <li class="icon icon-not-shipped">
              <%= t.harbor.name %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <blockquote>
        Not checked yet... Try to force update!
      </blockquote>
    <% end %>
  </p>
  </div>
<% end %>

app/views/issues/_changesets.html.erb
<% changesets.each do |changeset| %>
    <div class="changeset <%= cycle('odd', 'even') %>">
    <p><%= link_to_revision(changeset, changeset.repository,
                            :text => "#{l(:label_revision)} #{changeset.format_identifier}") %><br />
        <span class="author"><%= authoring(changeset.committed_on, changeset.author) %></span></p>
    <div class="wiki">
        <%= textilizable(changeset, :comments) %>
    </div>
      <% if changeset.shipped_changes.any? %>
        <% changeset.shipped_changes.each do |t| %>
          <% if t.shipped %>
            <span class="icon icon-shipped">
              <%= t.harbor.name %>
            </span>
            <br/>
          <% end %>
        <% end %>
    <% end %>
    </div>
<% end %>

app/views/will_ship/configure.html.erb
<div class="contextual">
  <%= link_to 'Create New Configuration', new_will_ship_path, :class => 'icon icon-add' %>
</div>

<h2>Will Ship Configurations</h2>
<table class="list">

  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Project
      </th>
      <th>
        Habor to Ship
      </th>
      <th>
        Rule
      </th>
      <th>
        Custom Field
      </th>
      <th>
      </th>
    </tr>
  </thead>

  <tbody>

  <% unless @harbors.any? %>
    <tr class="nodata">
      <td colspan="5">
          No Harbors to ship...
      </td>
    </tr>
  <% else %>
    <% @harbors.each do |harbor|%>
    <tr>
      <td>
        <%= harbor.name %>
      </td>
      <td>
        <%= link_to harbor.project.name, project_path(harbor.project) %>
      </td>
      <td align="center">
        <%= link_to harbor.url, harbor.url %>
      </td>
      <td align="center">
        <%= WillShip::LOOKUP_RULES.invert[harbor.lookup_rule] %>
      </td>
      <td align="center">
        <%= harbor.custom_field.try(:name) || '*NO FIELD*' %>
      </td>
      <td class="buttons">
          <%= link_to 'Delete', will_ship_path(harbor), :method => :delete, :data => {:confirm => l(:text_are_you_sure)}, :class => 'icon icon-del' %>
      </td>
    </tr>
    <% end %>
  <% end %>

  </tbody>

</table>

app/views/will_ship/empty_harbors.html.erb
<h2>Some Harbors broken</h2>
<p id="errorExplanation">Redmine can't find any commits here</p>
<p class="legend cal warning left">
<% @harbors.each do |h|  %>
    &mdash; <%= "#{h[0]} URL: #{h[1]}" %> unreachable or empty!<br/>
<% end %>
</p>

app/views/will_ship/new.html.erb
<h2>Create Harbor to Ship</h2>
<p class="legend cal warning left">
 You should point <b>Harbor</b> to staging/production site where the content of <b><code>git log --format="%H"</code></b> present.
</p>
<%= form_for :harbor, :url => { controller: :will_ship, action: :create }  do |f| %>
  <div class="box">
      <label> <h4> Label/Name <span class="required"> *</span></h4> </label>

    <p>
      <%= f.text_field :name %> <br />
    </p>

    <label>
      <h4>Redmine project <span class="required"> *</span> </h4>
    </label>

    <p>
      <%= f.select :project_id, options_for_select(@projects.map { |p| [p.name, p.id]})  %> <br />
    </p>

    <label> <h4> Project Endpoint with git log <span class="required"> *</span></h4> </label>

    <p>
      <%= f.text_field :url %> <br />
    </p>

    <label>
      <h4>Lookup Rules <span class="required"> *</span> </h4>
    </label>

    <p>
      <%= f.select :lookup_rule, options_for_select(WillShip::LOOKUP_RULES)  %> <br />
    </p>

    <label>
      <h4>Custom Field</h4>
      <small>Used as to set Yes/No marking Issues as shipped or not</small>
    </label>

    <p>
      <%= f.select :custom_field_id, options_for_select(@custom_fields.collect {|p| [ p.name, p.id ] }), {include_blank: '-- No Fields --'}  %> <br />
    </p>


  </div>


  <p>
    <%= submit_tag 'Create',:name=>'save' %>
    <%= link_to 'Cancel', :action => :configure %>
  </p>

<% end %>